'use strict';
var fs = require('fs');
var path = require('path');
var crypto = require('crypto');
var root = path.resolve(__dirname, '..');
var source = path.join(root, 'src', 'styles');
var target = path.join(root, 'public', 'css', 'app.css');
var order = [
  'main.css',
  'cyber.css',
  'hero-fidelity.css',
  'hero-motion.css',
  'hero-top-responsive.css',
  'wagner-visual-fix.css',
  'wagner-top-sniper.css',
  'hero-clean-v296.css',
  'hero-responsive-approved.css',
  'performance-safe.css',
  'scroll-ux.css',
  'impact-experience.css',
  'premium-uniform-v330.css'
];
var output = [
  '/* AUTO-GENERATED by scripts/build-css.js. Edit src/styles/*.css. */',
  ''
];
order.forEach(function (name) {
  var file = path.join(source, name);
  if (!fs.existsSync(file)) throw new Error('CSS source missing: ' + name);
  output.push('/* ===== ' + name + ' ===== */');
  output.push(fs.readFileSync(file, 'utf8').trim());
  output.push('');
});
fs.mkdirSync(path.dirname(target), { recursive: true });
var content = output.join('\n') + '\n';
fs.writeFileSync(target, content);
var digest = crypto.createHash('sha256').update(content).digest('hex').slice(0, 12);
console.log('CSS built:', path.relative(root, target), content.length + ' bytes', digest);
